name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Yarn
      run: npm install -g yarn

    - name: Set up Yarn Berry
      run: |
        yarn set version stable
        yarn --version

    - name: Install global dependencies
      run: |
        yarn global add gulp
        yarn global add bem-tools-core

    - name: Install project dependencies
      run: yarn install

    - name: Build project
      run: yarn run build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: dist
